#define PROTO_MEMBER1_ENC VMValue1
#define PROTO_MEMBER2_ENC VMValue4
#define PROTO_DEBUGISN_ENC VMValue3
#define PROTO_TYPEINFO_ENC VMValue2
#define PROTO_DEBUGNAME_ENC VMValue1

#define LSTATE_STACKSIZE_ENC VMValue3
#define LSTATE_GLOBAL_ENC VMValue3

#define CLOSURE_FUNC_ENC VMValue1
#define CLOSURE_CONT_ENC VMValue3
#define CLOSURE_DEBUGNAME_ENC VMValue4

#define TABLE_MEMBER_ENC VMValue1
#define TABLE_META_ENC VMValue1

#define UDATA_META_ENC VMValue2

#define TSTRING_HASH_ENC VMValue4
#define TSTRING_LEN_ENC VMValue2

#define GSTATE_TTNAME_ENC VMValue2
#define GSTATE_TMNAME_ENC VMValue2
